#!/bin/bash
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

function loadSource {
    FILE="${*}"

    if [ -f "${FILE}" ]; then
        source "${FILE}"
    fi
}

loadSource "${HOME}/.profile"

loadSource "${XDG_DATA_HOME}/bash/variables"
loadSource "${XDG_DATA_HOME}/bash/aliases"
loadSource "${XDG_DATA_HOME}/bash/functions"
loadSource "${XDG_DATA_HOME}/bash/prompt"
loadSource "${XDG_DATA_HOME}/bash/options"

loadSource "/usr/share/blesh/ble.sh"
loadSource "/usr/share/doc/pkgfile/command-not-found.bash"
