# If not running interactively, don't do anything
[[ $- != *i* ]] && return

function loadSource {
    FILE=$@

    if [ -f "${FILE}" ]; then
        source "${FILE}"
    fi
}


loadSource ~/.shell_prompt
loadSource ~/.shell_vars
loadSource ~/.shell_aliases

[ -f "/usr/share/blesh/ble.sh" ] && source "/usr/share/blesh/ble.sh"
