#!/bin/sh
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias sh=${SHELL}
alias sudo='sudo '
alias cd..='cd ..'
alias cd...='cd ../..'
alias cd....='cd ../../..'
alias cd.....='cd ../../../..'
alias cd......='cd ../../../../..'
alias cd="OLDPWD2=\${OLDPWD} && cd"
alias cd-="cd -"
alias cd--="__destDir=\${OLDPWD2} && cd \${__destDir}"
alias lsmnt='lsblk -l | tail -n +2 | awk '\''length($7) { print $1" => "$7 }'\'''
alias grep='grep -a --color --text'
alias pcregrep='pcregrep -a --color --text'
alias uptime='uptime -p && printf "since " && uptime -s'

if [ -n "${SSH_CLIENT}" ] || [ -n "${SSH_TTY}" ]; then
    alias ls='ls --color=auto -h'
    alias poweroff="echo Surely you don\'t mean to do that on the remote machine! && echo If you do, use \'command poweroff\' instead."
else
    alias ls='ls --color=auto -h --hyperlink=always'
fi


[ -f "/usr/bin/systemctl" ]     &&  alias systemctl='systemctl --no-pager -l -n20'
[ -f "/usr/bin/xterm" ]         &&  alias xterm='xterm -rv'
[ -f "/usr/bin/xprop" ]         &&  alias xprop-wmclass='xprop | grep "WM_CLASS"'
[ -f "/usr/bin/wget" ]          &&  alias wget-persistent='wget -c --retry-connrefused --waitretry=1 --read-timeout=10 --timeout=5 -t 0'
[ -f "/proc/acpi/bbswitch" ]    &&  alias bbswitch-status="awk '{print $2}' /proc/acpi/bbswitch"

[ -f "/usr/bin/alsi" ] && [ ! -f "/usr/bin/neofetch" ] && alias neofetch='alsi'
[ -f "/usr/bin/neofetch" ] && [ ! -f "/usr/bin/alsi" ] && alias alsi='neofetch'

if [ -f "/usr/bin/git" ]; then
    alias git="git --no-pager"
    alias git-push="git fetch && git push"
    alias git-pull="git fetch && git pull --rebase"
    alias git-commit="git fetch && __gitCommit"
fi

if [ -f "/usr/bin/tmux" ]; then
    alias tmux-new='tmux new -s'
    alias tmux-resume='tmux attach-session -t'
    alias tmux-list='tmux list-session'
fi

if [ "${OSTYPE}" = "cygwin" ]; then
    alias killall="taskkill /IM"
fi

### Package manager
local PACKAGE_MANAGER_CMD='sudo printf "" && ${PACKAGE_MANAGER}'
local CAN_PM_ALIAS_AUTOCOMPLETE=false

if [ "${PACKAGE_MANAGER}" == "paru" ]; then
    PACKAGE_MANAGER_CMD="${PACKAGE_MANAGER_CMD} --skipreview --noredownload --norebuild --sudoloop --bottomup"
elif [ "${PACKAGE_MANAGER}" == "yaourt" ]; then
    PACKAGE_MANAGER_CMD="${PACKAGE_MANAGER_CMD} --noconfirm"
fi

for COMPLETION_SOURCE in "/usr/share/bash-completion/completions/${PACKAGE_MANAGER}.bash" \
                         "/usr/share/bash-completion/completions/${PACKAGE_MANAGER}"; do
    if [ -f "${COMPLETION_SOURCE}" ]; then
        CAN_PM_ALIAS_AUTOCOMPLETE=true
        source "${COMPLETION_SOURCE}"
        break
    fi
done

alias yeet="${PACKAGE_MANAGER_CMD}"
${CAN_PM_ALIAS_AUTOCOMPLETE} && complete -F _${PACKAGE_MANAGER} yeet

### Fixes
[ -f "/usr/bin/monodevelop" ]   &&  alias monodevelop="GNOME_DESKTOP_SESSION_ID="" monodevelop"
[ -f "/usr/bin/dotnet" ]        &&  alias dotnet='TERM=xterm dotnet'
