#!/bin/sh
exec tail -n +3 $0

menuentry "PrimeOS" --class prime {
    set bootdir='/primeos'
    set root='(hd0,2)'

    linux $bootdir/kernel quiet root=/dev/ram0 androidboot.selinux=permissive acpi_sleep=s3_bios,s3_mode SRC=$bootdir DATA=/data REMOUNT_RW=1
    initrd $bootdir/initrd.img
}
