#!/bin/sh
exec tail -n +3 $0

menuentry "PrimeOS" {
  set root='(hd0,2)'
  linux /primeos/kernel quiet root=/dev/ram0 androidboot.selinux=permissive acpi_sleep=s3_bios,s3_mode SRC=/primeos DATA=/data REMOUNT_RW=1
  initrd /primeos/initrd.img
}
