#!/bin/bash
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

function loadShellRc {
    FILE="${*}"

    loadSource "${FILE}"
    loadSource "${FILE}_custom"
}

function loadSource {
    FILE="${*}"

    if [ -f "${FILE}" ]; then
        source "${FILE}"
    fi
}

loadSource "${HOME}/.profile"

loadShellRc "${XDG_DATA_HOME}/bash/variables"
loadShellRc "${XDG_DATA_HOME}/bash/aliases"
loadShellRc "${XDG_DATA_HOME}/bash/functions"
loadShellRc "${XDG_DATA_HOME}/bash/prompt"
loadShellRc "${XDG_DATA_HOME}/bash/options"

loadSource "/usr/share/blesh/ble.sh"
loadSource "/usr/share/doc/pkgfile/command-not-found.bash"

[ -f '/usr/bin/zoxide' ] && \
    eval "$(zoxide init bash)"
