#!/bin/sh
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

ROOT_PATH=""
[ -d "/data/data/com.termux" ] && ROOT_PATH="/data/data/com.termux/files"

ROOT_ETC="${ROOT_PATH}/etc"
ROOT_PROC="${ROOT_PATH}/proc"
ROOT_USR="${ROOT_PATH}/usr"
ROOT_USR_BIN="${ROOT_USR}/bin"

# Functions

function edit() {
    if [ -z "${EDITOR}" ]; then
        echo "ERROR: the \$EDITOR variable is not set!"
        return
    fi
    
    for FILE_PATH in "$@"; do
        if [ -f "${FILE_PATH}" ]; then
            if [ -w "${FILE_PATH}" ]; then
                "${EDITOR}" "${FILE_PATH}"
            else
                sudo "${EDITOR}" "${FILE_PATH}"
            fi
        else
            local FILE_DIR_PATH=$(dirname "${FILE_PATH}")

            if [ -w "${FILE_DIR_PATH}" ]; then
                "${EDITOR}" "${FILE_PATH}"
            else
                sudo "${EDITOR}" "${FILE_PATH}"
            fi
        fi
    done
}

function package_manager_command() {
    local OPERATION
    local PACKAGE_MANAGER
    local PACKAGE_MANAGER_COMMAND
    local PACKAGE_MANAGER_FAMILY

    OPERATION="${1}"

    if [[ "${OPERATION}" == 'info' ]] \
    || [[ "${OPERATION}" == '-Qi' ]]; then
        OPERATION='info' && shift
    elif [[ "${OPERATION}" == 'install' ]] \
      || [[ "${OPERATION}" == 'add' ]] \
      || [[ "${OPERATION}" == '-S' ]]; then
        OPERATION='install' && shift
    elif [[ "${OPERATION}" == 'list' ]] \
      || [[ "${OPERATION}" == '-Q' ]]; then
        OPERATION='list' && shift
    elif [[ "${OPERATION}" == 'search' ]]; then
        OPERATION='search' && shift
    elif [[ "${OPERATION}" == 'uninstall' ]] \
      || [[ "${OPERATION}" == 'del' ]] \
      || [[ "${OPERATION}" == '-Rns' ]]; then
        OPERATION='uninstall' && shift
    elif [[ "${OPERATION}" == 'update' ]] \
      || [[ "${OPERATION}" == '-Syy' ]]; then
        OPERATION='update' && shift
    elif [[ "${OPERATION}" == 'upgrade' ]] \
      || [[ "${OPERATION}" == '-Syu' ]]; then
        OPERATION='info' && shift
    else
        OPERATION='search'
    fi

    PACKAGE_MANAGER='unknown'
    PACKAGE_MANAGER_COMMAND='unknown'
    PACKAGE_MANAGER_FAMILY='unknown'

    if [ -e '/sbin/apk' ]; then
        PACKAGE_MANAGER='apk'
        PACKAGE_MANAGER_COMMAND="${PACAKGE_MANAGER}"
        PACKAGE_MANAGER_FAMILY='apk'
    elif [ -e '/usr/bin/apt' ]; then
        PACKAGE_MANAGER='apt'
        PACKAGE_MANAGER_COMMAND="sudo ${PACKAGE_MANAGER}"
        PACKAGE_MANAGER_FAMILY='apt'

        if [[ "${OPERATION}" != 'info' ]] \
        && [[ "${OPERATION}" != 'search' ]]; then
            PACKAGE_MANAGER_COMMAND="${PACKAGE_MANAGER_COMMAND} -y"
        fi
    elif [ -e '/usr/bin/paru' ]; then
        PACKAGE_MANAGER='paru'
        PACKAGE_MANAGER_COMMAND="${PACKAGE_MANAGER} --noredownload --norebuild --sudoloop --noconfirm --bottomup --color auto"
        PACKAGE_MANAGER_FAMILY='pacman'
    elif [ -e '/usr/bin/yay' ]; then
        PACKAGE_MANAGER='yay'
        PACKAGE_MANAGER_COMMAND="${PACKAGE_MANAGER} --noredownload --norebuild --sudoloop --noconfirm --bottomup --color auto"
        PACKAGE_MANAGER_FAMILY='pacman'
    elif [ -e '/usr/bin/yaourt' ]; then
        PACKAGE_MANAGER='yaourt'
        PACKAGE_MANAGER_COMMAND="${PACKAGE_MANAGER} --noconfirm"
        PACKAGE_MANAGER_FAMILY='pacman'
    elif [ -e '/usr/bin/pacman' ]; then
        PACKAGE_MANAGER='pacman'
        PACKAGE_MANAGER_COMMAND="sudo ${PACKAGE_MANAGER}"
        PACKAGE_MANAGER_FAMILY='pacman'
    fi

    sudo printf ''

    if [[ "${OPERATION}" == 'info' ]]; then
        if [[ "${PACKAGE_MANAGER_FAMILY}" == 'apk' ]]; then
            ${PACKAGE_MANAGER_COMMAND} info -e "${@}"
        elif [[ "${PACKAGE_MANAGER_FAMILY}" == 'apt' ]]; then
            ${PACKAGE_MANAGER_COMMAND} info "${@}"
        elif [[ "${PACKAGE_MANAGER_FAMILY}" == 'pacman' ]]; then
            ${PACKAGE_MANAGER_COMMAND} -Qi "${@}"
        fi
    elif [[ "${OPERATION}" == 'install' ]]; then
        if [[ "${PACKAGE_MANAGER_FAMILY}" == 'apk' ]]; then
            ${PACKAGE_MANAGER_COMMAND} add "${@}"
        elif [[ "${PACKAGE_MANAGER_FAMILY}" == 'apt' ]]; then
            ${PACKAGE_MANAGER_COMMAND} install "${@}"
        elif [[ "${PACKAGE_MANAGER_FAMILY}" == 'pacman' ]]; then
            ${PACKAGE_MANAGER_COMMAND} -S "${@}"
        fi
    elif [[ "${OPERATION}" == 'list' ]]; then
        if [[ "${PACKAGE_MANAGER_FAMILY}" == 'apk' ]]; then
            ${PACKAGE_MANAGER_COMMAND} info
        elif [[ "${PACKAGE_MANAGER_FAMILY}" == 'apt' ]]; then
            ${PACKAGE_MANAGER_COMMAND} list --installed
        elif [[ "${PACKAGE_MANAGER_FAMILY}" == 'pacman' ]]; then
            ${PACKAGE_MANAGER_COMMAND} -Q
        fi
    elif [[ "${OPERATION}" == 'search' ]]; then
        if [[ "${PACKAGE_MANAGER_FAMILY}" == 'apk' ]] \
        || [[ "${PACKAGE_MANAGER_FAMILY}" == 'apt' ]]; then
            ${PACKAGE_MANAGER_COMMAND} search "${@}"
        elif [[ "${PACKAGE_MANAGER_FAMILY}" == 'pacman' ]]; then
            ${PACKAGE_MANAGER_COMMAND} "${@}"
        fi
    elif [[ "${OPERATION}" == 'uninstall' ]]; then
        if [[ "${PACKAGE_MANAGER_FAMILY}" == 'apk' ]] \
        || [[ "${PACKAGE_MANAGER_FAMILY}" == 'apt' ]]; then
            ${PACKAGE_MANAGER_COMMAND} purge "${@}"
        elif [[ "${PACKAGE_MANAGER_FAMILY}" == 'pacman' ]]; then
            ${PACKAGE_MANAGER_COMMAND} -Rns "${@}"
        fi
    elif [[ "${OPERATION}" == 'update' ]]; then
        if [[ "${PACKAGE_MANAGER_FAMILY}" == 'apk' ]] \
        || [[ "${PACKAGE_MANAGER_FAMILY}" == 'apt' ]]; then
            ${PACKAGE_MANAGER_COMMAND} update
        elif [[ "${PACKAGE_MANAGER_FAMILY}" == 'pacman' ]]; then
            ${PACKAGE_MANAGER_COMMAND} -Syy
        fi
    elif [[ "${OPERATION}" == 'upgrade' ]]; then
        if [[ "${PACKAGE_MANAGER_FAMILY}" == 'apk' ]] \
        || [[ "${PACKAGE_MANAGER_FAMILY}" == 'apt' ]]; then
            ${PACKAGE_MANAGER_COMMAND} update
            ${PACKAGE_MANAGER_COMMAND} upgrade
        elif [[ "${PACKAGE_MANAGER_FAMILY}" == 'pacman' ]]; then
            ${PACKAGE_MANAGER_COMMAND} -Syu
        fi
    else
        echo 'Unknown operation.'
        return 1
    fi
}
