#!/bin/bash

shopt -s histappend     # Append to the Bash history, don't overwrite it
shopt -s autocd         # Change directory when a path is entered as a command
shopt -s checkwinsize   # Check window size after each command. Avoids occasional prompt overlap
