#!/bin/bash
COMMIT_MESSAGE=$(cat "${1}" | sed \
    -e 's/^\s*\(.*\)\s*$/\1/g' \
    -e 's/.*/\u&/')

[ -z "${COMMIT_MESSAGE}" ] && exit 1

BRANCH_NAME=$(git symbolic-ref --short HEAD 2>/dev/null)
COMMIT_PREFIX=""

if [ -n "${BRANCH_NAME}" ]; then
    COMMIT_PREFIX="${BRANCH_NAME}: "
    COMMIT_MESSAGE=$(echo "${COMMIT_MESSAGE}" | sed 's/^'"${COMMIT_PREFIX}"'//gI')
fi

if [[ ${COMMIT_MESSAGE} == Merge* ]]; then
    COMMIT_PREFIX=""
elif [ -n "${COMMIT_PREFIX}" ]; then
    if [ "${BRANCH_NAME}" == "main" ] || \
       [ "${BRANCH_NAME}" == "master" ]; then
        COMMIT_PREFIX=""
    fi
fi

#COMMIT_MESSAGE=$(echo "${COMMIT_MESSAGE}" | sed 's/.*/\u&/')

echo "${COMMIT_PREFIX}${COMMIT_MESSAGE}" > "${1}"
